version: '3.4'
services:
  web:
    image: furman9596/rpi-simple-home-automation:latest
    ports:
      - "5585:5585"
    depends_on:
      - mqttBroker
      
  mqttBroker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"